language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_install:
  - npm install -g grunt-cli
  - pip install codecov
after_script:
  - codeclimate-test-reporter < lcov.info
install:
  - npm install
  - npm test
after_success:
  - codecov
